# Generated by Django 5.0.6 on 2024-08-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0009_comment_creator_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
    ]
